import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <link
          rel="icon"
          type="image/vnd.microsoft.icon"
          href="http://localhost:3333/favicon.ico"
        />
      </head>
      <body className="path-frontpage page-node-type-page has-glyphicons">
        {children}
      </body>
    </html>
  );
}
