import Homepage from "@/components/Homepage";
import StaticLayout from "@/layouts/StaticLayout";
import Head from "next/head";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link
          rel="icon"
          type="image/vnd.microsoft.icon"
          href="https://www.smile.eu/themes/custom/smileeu/favicon.ico"
        />
      </Head>
      <StaticLayout>
        <Homepage />
      </StaticLayout>
    </>
  );
}
