import Homepage from "@/components/Homepage";
import DynamicLayout from "@/layouts/DynamicLayout";
import Head from "next/head";

export default function Layout() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link
          rel="icon"
          type="image/vnd.microsoft.icon"
          href="http://localhost:3333/favicon.ico"
        />
      </Head>
      <DynamicLayout>
        <Homepage />
      </DynamicLayout>
    </>
  );
}
