import { GetStaticProps, InferGetStaticPropsType } from "next";
import Head from "next/head";

import AsyncHomepage, { IData } from "@/components/AsyncHomepage";
import DynamicLayout from "@/layouts/DynamicLayout";

export default function Dynamic({
  data,
}: InferGetStaticPropsType<typeof getStaticProps>) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link
          rel="icon"
          type="image/vnd.microsoft.icon"
          href="https://www.smile.eu/themes/custom/smileeu/favicon.ico"
        />
      </Head>
      <DynamicLayout>
        <AsyncHomepage data={data} />
      </DynamicLayout>
    </>
  );
}

export const getStaticProps: GetStaticProps<{
  data: IData;
}> = async () => {
  const [cards, openSources, solutions, technologies] = await Promise.all([
    fetch("http://localhost:3333/last").then((r) => r.json()),
    fetch("http://localhost:3333/opensource").then((r) => r.json()),
    fetch("http://localhost:3333/solutions").then((r) => r.json()),
    fetch("http://localhost:3333/technologies").then((r) => r.json()),
  ]);
  const data: IData = {
    cards,
    openSources,
    solutions,
    technologies,
  };
  return { props: { data } };
};
