import DynamicHomepage from "@/components/DynamicHomepage/DynamicHomepage";
import DynamicLayout from "@/layouts/DynamicLayout/DynamicLayout";
import Head from "next/head";

export default function Dynamic() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <DynamicLayout>
        <DynamicHomepage />
      </DynamicLayout>
    </>
  );
}
