import Header from "./components/Header/Header";
import Footer from "./components/Footer/Footer";
import "./globals.css"

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="path-frontpage page-node-type-page has-glyphicons">
        <div
          className="dialog-off-canvas-main-canvas"
          data-off-canvas-main-canvas=""
        >
          <Header />
          <div
            role="main"
            className="main-container container-fluid js-quickedit-main-content"
          >
            <div className="row">{children}</div>
          </div>
          <Footer />
        </div>
      </body>
    </html>
  );
}
